CREATE DATABASE BOTINES
CHARACTER SET utf8 COLLATE utf8_general_ci;

USE BOTINES;

CREATE TABLE BOTIN(
CODIGO VARCHAR(5) NOT NULL PRIMARY KEY,
DESCRIPCION VARCHAR(60) DEFAULT '',
TALLA INT(3), CHECK( TALLA > 9 AND TALLA <1000),
INDUSTRIA VARCHAR(30) DEFAULT ''
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS CLASICO(
CODIGO VARCHAR(5) NOT NULL PRIMARY KEY,
MATERIAL VARCHAR(30) NOT NULL,
COLOR ENUM('CAFE','MARRON','NEGRO','CHAROL','BLANCO'),
FOREIGN KEY (CODIGO) REFERENCES BOTIN(CODIGO)
) ENGINE = InnoDB;

CREATE TABLE INDUSTRIAL(
CODIGO VARCHAR(5) NOT NULL PRIMARY KEY,
MODELO VARCHAR(30),
FOREIGN KEY (CODIGO) REFERENCES BOTIN(CODIGO)
) ENGINE = InnoDB;


CREATE TABLE CLIENTE(
CI INT(8) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(60) NOT NULL,
DIRECCION VARCHAR(30) DEFAULT '',
CELULAR INT(8) NULL
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS VENDEDOR(
ITEM INT(4) AUTO_INCREMENT PRIMARY KEY,
NOMBREV VARCHAR(50) NOT NULL,
TELEFONOV INT(8) NULL,
CIUDAD VARCHAR(40) NULL
) ENGINE = InnoDB AUTO_INCREMENT=100;

CREATE TABLE SUPERVICION(
ITEM INT(4) NOT NULL,
ITEMS INT(4) NOT NULL,
FECHA DATETIME DEFAULT NOW(),
PRIMARY KEY(ITEM, ITEMS),
FOREIGN KEY (ITEM) REFERENCES VENDEDOR(ITEM),
FOREIGN KEY (ITEMS) REFERENCES VENDEDOR(ITEM)
) ENGINE = InnoDB;

CREATE TABLE VENTA(
CODIGO VARCHAR(5) NOT NULL,
ITEM INT(4) NOT NULL,
CI INT(8) NOT NULL,
FECHA DATETIME, CHECK ( YEAR(FECHA)=2019),
COSTO FLOAT(6,2) DEFAULT 0.0,
IMPUESTO FLOAT(6,2), CHECK(IMPUESTO = COSTO * 0.15),
PRIMARY KEY (CODIGO,ITEM,CI),
FOREIGN KEY (CODIGO) REFERENCES BOTIN(CODIGO),
FOREIGN KEY (ITEM) REFERENCES VENDEDOR(ITEM),
FOREIGN KEY (CI) REFERENCES CLIENTE(CI)
) ENGINE = InnoDB;


INSERT INTO CLIENTE(CI,NOMBRE,DIRECCION) VALUES (25154554,'Marcela Miranda','Calle Junin');
SELECT * FROM CLIENTE;
INSERT INTO CLIENTE VALUES (25154556,'Emanuel Miranda','Calle Junin',7665656);
INSERT INTO VENDEDOR(NOMBREV,TELEFONOV,CIUDAD) VALUES ('Carlos Gomez', 436436,'Sucre');
INSERT INTO VENDEDOR(ITEM,NOMBREV,TELEFONOV,CIUDAD) VALUES (105,'Carlos Flores', 436436,'Tarija');
SELECT * FROM VENDEDOR;
UPDATE VENDEDOR SET NOMBREV='Carla Gomez' WHERE ITEM=100;
UPDATE VENDEDOR SET NOMBREV='Carla Gomez Flores' WHERE ITEM=100;