CREATE DATABASE SERVICIOS
CHARACTER SET utf8 COLLATE utf8_general_ci;

USE SERVICIOS;

CREATE TABLE IF NOT EXISTS SERVICIO(
NSER CHAR(5) NOT NULL PRIMARY KEY,
DESCRIPCION VARCHAR(100) DEFAULT ''
) ENGINE = InnoDB;

CREATE TABLE EMBALAJE(
NSER CHAR(5) NOT NULL PRIMARY KEY,
ESPECIFICACION VARCHAR(100) DEFAULT '',
FOREIGN KEY (NSER) REFERENCES SERVICIO(NSER)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS TRANSPORTE(
NSER CHAR(5) NOT NULL PRIMARY KEY,
PESO INT(3), CHECK (PESO BETWEEN 10 AND 999),
FOREIGN KEY (NSER) REFERENCES SERVICIO(NSER)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS USUARIO(
CI INT(9) NOT NULL PRIMARY KEY,
NOMBREU VARCHAR(60) NOT NULL,
CELULAR INT(8) DEFAULT 0
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
ITEM INT(5) AUTO_INCREMENT PRIMARY KEY,
NOMBREE VARCHAR(60) NOT NULL,
CIUDAD ENUM('ORURO', 'POTOSI', 'SUCRE','TARIJA', 'BENI'),
TELEFEONO INT(8) DEFAULT 0,
ITEMR INT(5) NULL,
FOREIGN KEY (ITEMR) REFERENCES FUNCIONARIO(ITEM)
) ENGINE =InnoDB AUTO_INCREMENT=2001;

CREATE TABLE IF NOT EXISTS ATENCION(
NSER CHAR(5) NOT NULL,
CI INT(9) NOT NULL,
ITEM INT(5) NOT NULL,
FECHA DATETIME, CHECK( YEAR(FECHA)=2024),
COSTO FLOAT(6,2) DEFAULT 0.0,
DESCUENTO FLOAT(6,2), CHECK (DESCUENTO = COSTO * 0.2),
PRIMARY KEY(NSER,CI,ITEM),
FOREIGN KEY (NSER) REFERENCES SERVICIO(NSER),
FOREIGN KEY (CI) REFERENCES USUARIO(CI),
FOREIGN KEY (ITEM) REFERENCES FUNCIONARIO(ITEM)
) ENGINE = InnoDB;




