USE REPUESTOS;
SELECT * FROM COMPRA;
-- Procedimiento almacenado que muestre el costo total a pagar menos el descuento y más el impuesto de la compra 
-- de repuestos que realizó cada proveedor cuyo descuento no sea inferior al descuento más bajo de las compras 
-- del año 2020. Incluyendo solamente los proveedores cuya cantidad total de compra es por lo menos 10.
DELIMITER $$
CREATE PROCEDURE EXA1()
BEGIN
DECLARE DMIN FLOAT(6,2);
SELECT MIN(DESCUENTO) INTO DMIN FROM COMPRA WHERE YEAR(FECHA)=2019;

SELECT P.NOMBREP AS 'PROVEEDOR',
	SUM(C.COSTO -C.DESCUENTO + C.IMPUESTO) AS 'COSTO TOTAL'
FROM COMPRA C INNER JOIN PROVEEDOR P ON C.NIT=P.NIT
WHERE C.DESCUENTO>=DMIN 
GROUP BY P.NOMBREP
HAVING SUM(C.CANTIDAD) >=10;
END $$
DELIMITER ;

CALL EXA1();
-- Procedimiento almacenado que muestre la cantidad de repuestos eléctricos y la cantidad de repuestos mecánicos
-- que se ha comprado a un proveedor en un día y mes del año actual en curso (obtenido del sistema). Se tiene 
-- como datos el NIT del proveedor, el día y mes de la compra.
DELIMITER $$
CREATE PROCEDURE EXA2(IN NP CHAR(10), IN DIA INT, IN MES INT)
BEGIN
DECLARE CE INT;
DECLARE CM INT;

SELECT SUM(C.CANTIDAD) INTO CE
FROM COMPRA C INNER JOIN ELECTRICO E ON C.CODIGO=E.CODIGO
WHERE C.NIT = NP AND DAY(C.FECHA)=DIA AND MONTH(C.FECHA)=MES;

SELECT SUM(C.CANTIDAD) INTO CM
FROM COMPRA C INNER JOIN MECANICO M ON C.CODIGO=M.CODIGO
WHERE C.NIT = NP AND DAY(C.FECHA)=DIA AND MONTH(C.FECHA)=MES;

SELECT CE AS 'REPUESTOS ELECTRICOS',
CM AS 'REPUESTOS MECANICOS';
END $$
DELIMITER $$

CALL EXA2('1011222450',5,5);
SELECT * FROM COMPRA;

-- Procedimiento almacenado que devuelva en parámetro salida la cantidad de repuestos eléctricos con una potencia
-- superior a los 1000 watts, que les han entregado a dos encargados cuyos nombres se tienen como datos.
DELIMITER $$
CREATE PROCEDURE EXA3(IN NE1 VARCHAR(50), IN NE2 VARCHAR(50), OUT CE INT)
BEGIN 
DECLARE IE1 INT(6);
DECLARE IE2 INT(6);
IF EXISTS(SELECT * FROM ENCARGADO WHERE NOMBRE=NE1)THEN
IF EXISTS(SELECT * FROM ENCARGADO WHERE NOMBRE= NE2) THEN

SELECT ITEM INTO IE1 FROM ENCARGADO WHERE NOMBRE=NE1;
SELECT ITEM INTO IE2 FROM ENCARGADO WHERE NOMBRE = NE2;

SELECT SUM(E.CANTIDADE) INTO CE
FROM ENTREGA E INNER JOIN ELECTRICO L ON E.CODIGO=L.CODIGO
WHERE E.ITEM IN (IE1,IE2) AND L.POTENCIA>1000;
ELSE SELECT 'ENCARGADO 2 NO REGISTRADO' AS MENSAJE; END IF;
ELSE SELECT 'ENCARGADO 1 NO REGISTRADO' AS MENSAJE; END IF;
END $$
DELIMITER ;
CALL EXA3('VICTOR CASTEDO','CARLOS GOMES',@CEL);
SELECT @CEL AS 'CANTIDAD RESPUESTOS ELECTRICOS';

SELECT * FROM ENTREGA;
SELECT * FROM ENCARGADO;
-- Función que devuelva la mayor cantidad de compra de repuestos realizada a un proveedor en una determinada fecha. 
-- El nombre del proveedor y la fecha se introducen como argumentos.

DELIMITER $$
CREATE FUNCTION EXA4( NP VARCHAR(50), FECH DATE) RETURNS INT
READS SQL DATA DETERMINISTIC
BEGIN
DECLARE MAXCAN INT;
DECLARE NIP CHAR(10);

SELECT NIT INTO NIP FROM PROVEEDOR WHERE NOMBREP=NP;

SELECT MAX(CANTIDAD) INTO MAXCAN
FROM COMPRA 
WHERE NIT=NIP AND DATE(FECHA)=FECH;

RETURN MAXCAN;
END $$
DELIMITER ;

SET @MXC = EXA4('JUAN CARLOS', '2019-05-05');
SELECT @MXC AS 'MAYOR CANTIDAD DE COMPRA';

SELECT * FROM COMPRA;
SELECT * FROM PROVEEDOR;